### ISSUE TITLE
Unable to include Kotlin Jar dependencies

### ISSUE THREAD

**Issue by jmmk** [bazelbuild/rules_kotlin#18]
Same issue that I had with the original `rules_kotlin`: https://github.com/pubref/rules_kotlin/issues/40
Fix for that issue: https://github.com/pubref/rules_kotlin/pull/41

Here's a gist that should reproduce: https://gist.github.com/jmmk/0d73714ffec4efefbe0d0b1858a783df

Am I doing something wrong or does something need to be changed to properly support this?

**Comment by hsyed** [comment]
@jmmk what error do you get ? 

I see that you are using `maven_repositories`  directly. `java_import` produces an ijar and is stripping off Kotlin inlining data.  Maven repositories will use `java_import` under the covers.

There is an issue open for this in [bazel core](https://github.com/bazelbuild/bazel/issues/4549) to fix the ijar tool, once this is done `java_import` can be used without problems. Till then if you need to import kotlin jars use `kt_jvm_import`. 

Also notice that your `maven_repositories` rule is pulling in kotlin dependencies (of a different version). You will have to omit these in `maven_repositories`, the `stdlib`, `stdlib-jdk7` and `stdlib-jdk8` are added implicitly by the rules. If the Jackson kotlin dep does not including inlined functions things might start working, otherwise you have to use `kt_jvm_import` for the time being.

**Comment by jmmk** [comment]
The error is:

```
ERROR: /Users/jmmk/Desktop/bazel-kotlin/BUILD:2:1: Compiling 1 Kotlin source files to main.jar failed (Exit 1)
App.kt:1:44: error: unresolved reference: jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
                                           ^
App.kt:4:16: error: unresolved reference: jacksonObjectMapper
  val mapper = jacksonObjectMapper()
 ```

See the issues/PR linked above as well as https://github.com/bazelbuild/bazel/issues/4297 for more technical details. Maybe related to your issue?

I'll try out `kt_jvm_import`, thanks!

**Comment by hsyed** [comment]
this file which includes the file containing jacksonObjectMapper is full of [inline functions](https://github.com/FasterXML/jackson-module-kotlin/blob/master/src/main/kotlin/com/fasterxml/jackson/module/kotlin/Extensions.kt)

**Comment by hsyed** [comment]
Closing this please reopen if there are other issues.
