### ISSUE TITLE
Feature request: don't show Java compilation errors if Kotlin completion errors exist

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/rules_kotlin#227]
I spent too long trying to chase down Java compilation errors only to find out the underlying issue was in Kotlin. 

In the stdout Java issues showed up on top of the Kotlin issues so I spent hours trying to fix those before even noticing the Kotlin issues.

From the source code it looks like we compile Kotlin first.

**Comment by cgruber** [comment]
We don't compile kotlin first, it's weirder than that. We generate java stubs from the kotlin in order to compile java first.  So we don't "compile" kotlin first, but we do parsing/lexing of kotlin, so errors in the kotlin can end up being proximally located in java compilation errors, because the kotlin errors weren't surfaced during stub generation. 

This is high-priority, but hard, so it probably won't be fixed in the imminent 1.3.  But I'll make it a high priority fix for 1.4

**Comment by cgruber** [comment]
I'm not sure if this can be fixed without a pretty big redesign, insofar as this is happening because generating java stubs from the kotlin is failing, so the java isn't there.  Fixing this means major surgery on how we stage the compile.

That said, we need that for performance anyway, so I'll have this as a 1.4.0 goal, but I've got to downgrade it to P2, because it's not clear we can make that happen.

**Comment by cgruber** [comment]
This issue is pretty old, and a lot has changed. It also requires a fair bit of rework of the compiler handling, so unless we have a more concrete path to this, I'm going to say it's not going to happen.
