### ISSUE TITLE
Error when use kt_android_library and cc_library together in the same BUILD.bazel file.

### ISSUE THREAD

**Issue by AndrewChupin** [bazelbuild/rules_kotlin#305]
I have a BUILD.bazel file and when i'm trying to build it i get an error:

```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")


PACKAGE_NAME = "examples.android.ndk"
kt_android_library(
    name = "ndk-lib",
    srcs = glob(["src/main/kotlin/**/*.java"]),
    custom_package = PACKAGE_NAME,
    manifest = "src/main/AndroidManifest.xml",
    visibility = ["//visibility:public"],
    deps = [
        ":jni_lib",
        "@maven//:androidx_appcompat_appcompat",
    ],
)

cc_library(
    name = "import_lib",
    srcs = glob([
        "src/main/libs/**/*.so",
    ]),
)
```

> in deps attribute of kt_jvm_library rule //ndk-lib:ndk-lib_kt: '//ndk-lib:jni_lib' does not have mandatory providers: 'JavaInfo'. Since this rule was created by the macro 'kt_android_library', the error might have been caused by the macro implementation

Everything is alright if i'm trying to build project just with `android_library` instead `kt_android_library`

**Comment by AndrewChupin** [comment]
P.S. i saw this error in an another bazel rules and usually it's library's problem.

**Comment by rockwotj** [comment]
cc_library is not a dep, but should be listed as a resource and then dynamically extracted and loaded at runtime.

This is not something that Java or kotlin rules allow.

**Comment by AndrewChupin** [comment]
I can't use it inside one file, i'm getting an exception. But with android_library(not kt_android_library) it works proprely.

**Comment by cgruber** [comment]
So, what is likely happening here is that android_library has special case logic for handling non-java sources, but kt_android_library is a thin wrapper macro around a kt_jvm_library and an android_library. As such, it can't gain access to the providers to pull out JavaInfo where needed, and other providers where needed. In order to do this (at least for now, until the android rules are in starlark and we can construct a better kt_android_library, you'll need to make a small android_library target that consumes the jni and ends up being a library that can be included in the kt_android_library.  It sucks to add that extra piece of indirection, but with the current design of kt_android_library there's no way to fix this. (We have ideas in the long-run, but for now, you'll have to work around).

I have in mind something like: 

```
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")


PACKAGE_NAME = "examples.android.ndk"
kt_android_library(
    name = "ndk-lib",
    srcs = glob(["src/main/kotlin/**/*.java"]),
    custom_package = PACKAGE_NAME,
    manifest = "src/main/AndroidManifest.xml",
    visibility = ["//visibility:public"],
    deps = [
        ":jni_lib",
        "@maven//:androidx_appcompat_appcompat",
    ],
)

android_library(
  name = "jni_lib",
  runtime_deps = [
    ":import_lib",
  ],
)

cc_library(
    name = "import_lib",
    srcs = glob([
        "src/main/libs/**/*.so",
    ]),
)
```

**Comment by cgruber** [comment]
For now I'm going to close this, as we won't be able to fix this short-term. I'll reference it in another issue once we get the necessary ingredients to construct a kt_android_library as a proper rule.
