### ISSUE TITLE
Associates attribute doesn't work with kt_android_local_test

### ISSUE THREAD

**Issue by Nikolas-LFDesigns** [bazelbuild/rules_kotlin#540]
I'm working on a test which works with internal class fields. Kotlin supports adding a "friends" module which opens up its internal members to a declaring entities. I found out the following description about special "associates" attribute here https://github.com/bazelbuild/rules_kotlin/pull/465, which suits my needs.

> Android should work, but because kt_android_* is a macro not a rule, the implicit target //my/android/library:mytarget_kt should be friended, since it has a KtJvmInfo. The //my/android/library will macro-resolve into an android_library. Until the android rules get the right kind of love, such that we can make a rule that has KtJvmInfo AND android-whatever providers, this simply is a known limitation we'll have to live with.

Unfortunately, the statement above is not completely realized in a project. 
An error is:
```
in kt_jvm_library rule //testproject/src/test/java/com/test:LocalTest_kt: target '//testproject/src/main/java/com/test:test_kt' is not visible from target '//testproject/src/test/java/com/test:LocalTest_kt'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
This does not work because kt_jvm_library meant to be exposed the way described earlier is actually private by definition and seemingly should remain so (https://github.com/bazelbuild/rules_kotlin/blob/5357ac1a1d25e6ce083c0cb7ee489012d396177d/kotlin/internal/jvm/android.bzl#L57). 

Minimal example omitting standard stuff like rule definitions and basic trivial stuff:
**Local.kt:**
```
package com.test

class Local {
  internal fun doSomething(): Int = 0
}
```
**testproject/src/main/java/com/test/BUILD.bazel:**
```
kt_android_library(
    name = "test",
    srcs = [
        "Local.kt",
    ],
)
```
**LocalTest.kt:**
```
package com.test

@RunWith(JUnit4::class)
class LocalTest {
  @Test
  fun doSomething(): {
    LocalTest().doSomething()
  }
}
```
**testproject/src/test/java/com/test/BUILD.bazel:**
```
kt_android_local_test(
    name = "LocalTest",
    srcs = [
        "LocalTest.kt",
    ],
    associates = [
        "//testproject/src/main/java/com/test:test_kt",
    ]
    deps = [
        "//testproject/src/main/java/com/test:test",
        "@junit_junit",
    ],
)
```

Is there any way to make it work on an android tests without further exposing a library? Or should it be exposed?

@cgruber

**Comment by cgruber** [comment]
So I'm unable to reproduce this initially - if the test target is in the same bazel package, then it works (so spec'ing your tests at the root). But it does break if you're not in the same package. I think we have to make it `//visibility:public` until we can avoid the "android sandwich" issue of our current macro approach to the android rules.

**Comment by cgruber** [comment]
Fix underway.

**Comment by oliviernotteghem** [comment]
@cgruber : we're hitting this issue too, even after the fix :( 

Here is how to repro: 

1. apply attached patch
2. bazel test projects/core/impl/src/test/kotlin/core/impl:CoreImplTest

Result: 
`ERROR: /Users/oliviern/rules_kotlin/examples/associates/projects/core/impl/src/test/kotlin/core/impl/BUILD.bazel:3:12: in associates attribute of kt_jvm_test rule //projects/core/impl/src/test/kotlin/core/impl:CoreImplTest: '//projects/core/api:android_api' does not have mandatory providers: 'KtJvmInfo'. Since this rule was created by the macro 'kt_jvm_test', the error might have been caused by the macro implementation`

[540_patch.txt](https://github.com/bazelbuild/rules_kotlin/files/7952974/540_patch.txt)

**Comment by cgruber** [comment]
You cannot depend on `//projects/core/api:android_api` in the `associates=` property, as that is not a target that exposes KtJvmInfo. AGain, this is because of the "android sandwich" macro approach which we must use, until we can roll a full android-kotlin rule (which requires that the android stuff all be starlark). 

For now, you can depend on `<your_target>_kt` (e.g. `//projects/core/api:android_api_kt`) and that should get you what you need.
