### ISSUE TITLE
"cannot find symbol" when compiling `kt_jvm_library` including Java which references Kotlin

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_kotlin#707]
Repro repo here: https://github.com/illicitonion/rules_kotlin-mixed-compile-repro

It looks like https://github.com/bazelbuild/rules_kotlin/pull/694 broke compiling mixed libraries in some way...

**Comment by Bencodes** [comment]
@illicitonion thanks for reporting this. Looks like this is broken because we are returning a non-empty depset for annotation processing, despite there being no annotation processors to run. This kicks the compilation down the Kapt path which isn't a valid state to be in.

This appears to fix the issue already https://github.com/bazelbuild/rules_kotlin/pull/685/files
